### ISSUE TITLE
cashier

### ISSUE THREAD

**Issue by tfranca2** [tfranca2/blackhostel#21]
Add cashier module. 4 basic opperations: opening cash, closing cash, cash drain and resupply.
The form will contain a combobox with a ENUM of the operations and its value, datetime and user will come to system.

**Comment by jocelio** [comment]
Will these functions be available in reserves view?

**Comment by tfranca2** [comment]
I thought in a separate module.

**Comment by jocelio** [comment]
would be good to have these models in our diagram.

   -

2015-10-23 9:22 GMT-03:00 Tiago França notifications@github.com:
